### ISSUE TITLE
errors when compiling

### ISSUE THREAD

**Issue by josecoma** [rundeck-plugins/save-to-file#1]
Hello,

I was trying to compile the zip file with gradle but I get the below error

Could not find method plugins() for arguments [build_1qprte0kgu2euvc244umcodm5p$_run_closure1@5a445a44] on root project 'save-to-file-0.1.2'.

Any idea? Would you mind to provide a .jar file for me? sorry I'm a bit newbie 🥇 

Thanks in advance!

**Comment by ltamaster** [comment]
closed with https://github.com/rundeck-plugins/save-to-file/pull/2
